# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TemplateRN59' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for TemplateRN59
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTPushNotification',
  ]
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'react-native-rsa-native', :path => '../node_modules/react-native-rsa-native'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'TemplateRN59Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
